[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
leptos = { version = "0.2.5" } 
wasm-bindgen = "0.2"
log = "0.4"
console_error_panic_hook = "0.1"
console_log = "1"

app = { path = "../app", features = ["hydrate"] }

